name: Android CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Detekt Report to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report-artifacts
          path: |
            app/build/reports/lint-results-debug.html
